#!/usr/bin/env python3
"""Regenerate the landing site's release + roadmap content from JSON.

Owns five things:
  1. The "New in X" section of docs/index.html (between WN:BEGIN/WN:END
     markers), rendered from the newest release, plus the hero version string.
  2. docs/releases.html, the full categorized changelog, rendered whole.
  3. docs/roadmap.html, the status board (considering / planned / building /
     shipped), rendered whole from docs/roadmap.json.
  4. The "## Roadmap" block in README.md (between ROADMAP:BEGIN/END markers),
     a compact mirror of the board.
  5. The hero download count and GitHub star count (DL:/STARS: markers), but
     only under --stats: they move on their own, so --check must not see them.

Usage:
  python3 scripts/site-release.py               # regenerate everything
  python3 scripts/site-release.py --check       # exit 1 if output would change (CI)
  python3 scripts/site-release.py --list-icons  # show valid icon + color names
  python3 scripts/site-release.py --stats       # also refresh download + star counts

Stdlib only. Keep it that way, this runs in the Pages deploy job.
"""

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
DATA = DOCS / "releases.json"
INDEX = DOCS / "index.html"
HISTORY = DOCS / "releases.html"
ROADMAP = DOCS / "roadmap.json"
ROADMAP_HTML = DOCS / "roadmap.html"
README = ROOT / "README.md"
INSTALL_HTML = DOCS / "install.html"
COMPARE = DOCS / "compare.json"
COMPARE_HTML = DOCS / "compare.html"
BLOG_DIR = DOCS / "blog"
BLOG_JSON = DOCS / "blog.json"
BLOG_INDEX = BLOG_DIR / "index.html"
SITEMAP = DOCS / "sitemap.xml"
ROBOTS = DOCS / "robots.txt"
CHROME_CSS_FILE = DOCS / "assets" / "chrome.css"
DOCS_JSON = DOCS / "docs.json"
DOCS_HTML = DOCS / "docs.html"
STATS = DOCS / "stats.json"

WN_BEGIN = "<!-- WN:BEGIN generated by scripts/site-release.py; edit docs/releases.json instead -->"
WN_END = "<!-- WN:END -->"
RM_BEGIN = "<!-- ROADMAP:BEGIN generated by scripts/site-release.py; edit docs/roadmap.json instead -->"
RM_END = "<!-- ROADMAP:END -->"
DL_BEGIN = "<!-- DL:BEGIN generated by scripts/site-release.py; counts come from GitHub releases -->"
DL_END = "<!-- DL:END -->"
PICK_BEGIN = "<!-- PICK:BEGIN generated by scripts/site-release.py -->"
PICK_END = "<!-- PICK:END -->"
NAV_BEGIN = "<!-- NAV:BEGIN generated by scripts/site-release.py -->"
NAV_END = "<!-- NAV:END -->"

REPO = "https://github.com/caezium/Burrow"
SITE = "https://burrow.computer"
SITE_HOST = "burrow.computer"

# Jewel tokens that exist as CSS variables in the site stylesheet.
COLORS = {"teal", "coral", "violet", "azure", "gold", "moss", "ginger",
          "green", "red", "lilac", "apricot", "mint", "accent"}

# Roadmap item types → CSS badge classes.
RTYPES = {"feat", "fix", "infra"}

# Small stroke-icon library (24×24, stroke = currentColor handled by CSS).
ICONS = {
    "home":        '<path d="M4 11l8-7 8 7"/><path d="M6 9.5V20h12V9.5"/><path d="M10 20v-5h4v5"/>',
    "globe":       '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.6 2.5 4 5.6 4 9s-1.4 6.5-4 9c-2.6-2.5-4-5.6-4-9s1.4-6.5 4-9z"/>',
    "thermo":      '<path d="M14 14.8V5a2 2 0 10-4 0v9.8a4 4 0 104 0z"/><path d="M12 11v6"/>',
    "pulse":       '<path d="M3 12h4l2.5-7 4 14 2.5-7h5"/>',
    "trash":       '<path d="M4 7h16M9 7V5h6v2M6 7l1 13h10l1-13"/><path d="M10 11v5M14 11v5"/>',
    "sparkle":     '<path d="M12 4l1.8 4.6L18 10l-4.2 1.4L12 16l-1.8-4.6L6 10l4.2-1.4z"/><path d="M18.5 15.5l.9 2.1 2.1.9-2.1.9-.9 2.1-.9-2.1-2.1-.9 2.1-.9z"/>',
    "wrench":      '<path d="M14.7 6.3a1 1 0 000 1.4l1.6 1.6a1 1 0 001.4 0l3.77-3.77a6 6 0 01-7.94 7.94l-6.91 6.91a2.12 2.12 0 01-3-3l6.91-6.91a6 6 0 017.94-7.94l-3.76 3.76z"/>',
    "flask":       '<path d="M10 3v6L4.5 18a2 2 0 001.8 3h11.4a2 2 0 001.8-3L14 9V3"/><path d="M8.5 3h7M7 15h10"/>',
    "package":     '<path d="M21 8l-9-5-9 5v8l9 5 9-5z"/><path d="M3 8l9 5 9-5M12 13v8"/>',
    "gauge":       '<path d="M5 19a9 9 0 1114 0"/><path d="M12 13l4-4"/><circle cx="12" cy="13" r="1.6"/>',
    "chart":       '<path d="M4 20v-6M9 20V8M14 20v-9M19 20V5"/>',
    "list":        '<path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/>',
    "sweep":       '<path d="M9.59 4.59A2 2 0 1111 8H2m10.59 11.41A2 2 0 1014 16H2m15.73-8.27A2.5 2.5 0 1119.5 12H2"/>',
    "robot":       '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 9l3 3-3 3M13 15h4"/>',
    "shield":      '<path d="M12 3l7 3v5c0 4.5-3 8-7 10-4-2-7-5.5-7-10V6z"/><path d="M9.5 11.5l2 2 3.5-3.5"/>',
    "leaf":        '<path d="M5 19C5 9 13 4 20 4c0 7-3 15-13 15"/><path d="M5 19c2-5 6-9 11-11"/>',
    "fingerprint": '<path d="M4.5 9.5A8 8 0 0120 12"/><path d="M7 12a5 5 0 0110 0c0 3-1 6-2.5 8"/><path d="M12 12c0 3-.6 5.5-1.8 7.6"/>',
    "monitor":     '<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M3 8h18M9 21h6"/>',
    "clock":       '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    "layout":      '<rect x="3" y="3" width="8" height="11" rx="1"/><rect x="13" y="3" width="8" height="6" rx="1"/><rect x="13" y="11" width="8" height="10" rx="1"/><rect x="3" y="16" width="8" height="5" rx="1"/>',
    "key":         '<circle cx="8" cy="15" r="4"/><path d="M10.8 12.2L20 3l1 1-2 2M16 8l2 2"/>',
}

CHECK_PATH = '<path d="M5 13l4 4L19 7"/>'

MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]

def logo_img(base=""):
    """The real app icon, not a hand-drawn approximation of it."""
    return (f'<img class="mk" src="{base}burrow-icon.png" alt="" width="28" height="28" '
            f'decoding="async">')

GITHUB_SVG = ('<svg class="icon icon--github" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">'
              '<path d="M12 .5a12 12 0 00-3.8 23.4c.6.1.8-.3.8-.6v-2c-3.3.7-4-1.6-4-1.6-.6-1.4-1.3-1.8-1.3-1.8'
              '-1.1-.7 0-.7 0-.7 1.2 0 1.9 1.2 1.9 1.2 1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3'
              '-5.5-5.9 0-1.3.5-2.4 1.2-3.2-.1-.3-.5-1.5.1-3.2 0 0 1-.3 3.3 1.2a11.5 11.5 0 016 0C17.3 5 18.3 '
              '5.3 18.3 5.3c.6 1.7.2 2.9.1 3.2.8.8 1.2 1.9 1.2 3.2 0 4.6-2.8 5.6-5.5 5.9.4.4.8 1.1.8 2.2v3.3c0 '
              '.3.2.7.8.6A12 12 0 0012 .5z"/></svg>')

APPLE_SVG = ('<svg class="icon icon--apple" viewBox="0 0 814 1000" aria-hidden="true">'
             '<path d="M788.1 340.9c-5.8 4.5-108.2 62.2-108.2 190.5 0 148.4 130.3 200.9 134.2 202.2-.6 3.2-20.7 '
             '71.9-68.7 141.9-42.8 61.6-87.5 123.1-155.5 123.1s-85.5-39.5-164-39.5c-76.5 0-103.7 40.8-165.9 '
             '40.8s-105.6-57-155.5-127C46.7 790.7 0 663 0 541.8c0-194.4 126.4-297.5 250.8-297.5 66.1 0 121.2 '
             '43.4 162.7 43.4 39.5 0 101.1-46 176.3-46 28.2 0 129.8 2.6 196.3 99.2zm-234-181.1c31.1-36.9 '
             '53.1-88.1 53.1-139.3 0-7.1-.6-14.3-1.9-20.1-50.6 1.9-110.8 33.7-147.1 75.8-28.2 32.4-54.4 '
             '84.4-54.4 136.5 0 7.8 1.3 15.6 1.9 18.1 3.2.6 8.4 1.3 13.6 1.3 45.4 0 102.5-30.4 135.8-71.3z"/></svg>')


def render_nav(active, base="", stars=None):
    """The single top bar every page uses. `active` highlights a nav link,
    `base` is the relative prefix back to docs/ for pages in a subdirectory."""
    def link(href, label, key):
        on = ' class="on"' if active == key else ""
        return f'<a href="{base}{href}"{on}>{label}</a>'
    count = f'<span class="nav-stars">{compact(stars)}</span>' if stars else ""
    # Which translated page this nav sits on. Pages that exist only in English
    # (install, blog) point the picker at each language's home rather than at a
    # path that would 404 in nine languages.
    page_path = {"tools": "", "docs": "docs", "compare": "compare",
                 "changelog": "releases", "roadmap": "roadmap"}.get(active, "")
    return f"""<div class="topbar">
  <div class="page in">
    <a class="brand" href="{base}./" aria-label="Burrow">{logo_img(base)}<span>Burrow</span></a>
    <nav class="nav">{link("./#tools", "Tools", "tools")}\
{link("docs", "Docs", "docs")}\
{link("compare", "Compare", "compare")}\
{link("blog/", "Blog", "blog")}\
{link("install", "Install", "install")}\
{link("releases", "Changelog", "changelog")}\
{link("roadmap", "Roadmap", "roadmap")}</nav>
    <div class="nav-right">
      {lang_picker(page_path)}
      <a class="nav-github" href="{REPO}" target="_blank" rel="noopener" aria-label="View Burrow on GitHub">{GITHUB_SVG}{count}</a>
      <a class="btn" href="{base}install" data-burrow-analytics="download.{active}"><span class="btn-inner">{APPLE_SVG}<span class="nav-label--full">Download for Mac</span><span class="nav-label--short">Download</span></span></a>
    </div>
  </div>
</div>"""


def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def md_links(s):
    """Escape HTML, then convert `code`, **bold**, and [text](url) markup."""
    out = esc(s)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", out)
    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)",
                  r'<a href="\2" target="_blank" rel="noopener">\1</a>', out)


def month_year(iso):
    y, m, _ = (int(p) for p in iso.split("-"))
    return f"{MONTHS[m - 1]} {y}"


def pretty_date(iso):
    y, m, d = (int(p) for p in iso.split("-"))
    return f"{MONTHS[m - 1][:3]} {d}, {y}"


def icon_svg(name):
    return ('<svg viewBox="0 0 24 24" stroke-linecap="round" '
            f'stroke-linejoin="round">{ICONS[name]}</svg>')


CHROME_CSS = """/* GENERATED by scripts/site-release.py; do not edit by hand.
   The top bar, buttons, and footer for every page on the site. Both the
   hand-written landing page and the generated pages link this file, so the
   chrome cannot drift between them. */

.topbar { position: sticky; top: 0; z-index: 50; padding-top: 16px; margin-bottom: -8px; }
.topbar .page { width: 100%; max-width: 1080px; margin: 0 auto; padding: 0 24px; }
.topbar .in {
  height: 60px; display: flex; align-items: center; justify-content: space-between;
  gap: 16px; padding: 0 10px 0 16px; border-radius: 999px;
  border: 1px solid rgba(243,236,221,0.13); background: rgba(18,18,23,0.72);
  -webkit-backdrop-filter: saturate(150%) blur(14px); backdrop-filter: saturate(150%) blur(14px);
  box-shadow: 0 1px 2px rgba(0,0,0,0.28);
}
.brand { display: flex; align-items: center; gap: 10px; font-family: "Geist", -apple-system, system-ui, sans-serif;
  font-size: 1.05rem; font-weight: 600; letter-spacing: -0.02em; color: #F3ECDD;
  text-decoration: none; transition: transform .18s; }
.brand:hover { transform: scale(1.03); }
.brand .mk, .brand-logo { width: 28px; height: 28px; border-radius: 8px; flex: none; }

/* Language picker, filled in by scripts/site-i18n.py. A bare <details> so it
   opens with no JavaScript — the translated pages are the one place a visitor
   may not read enough English to debug a menu that needs a script. */
.langpick { position: relative; }
.langpick > summary { list-style: none; cursor: pointer; user-select: none;
  display: inline-flex; align-items: center; gap: 6px; padding: 5px 10px;
  border-radius: 999px; font-size: 13px; color: rgba(243,236,221,0.66);
  border: 1px solid rgba(243,236,221,0.14); }
.langpick > summary::-webkit-details-marker { display: none; }
.langpick > summary::after { content: ""; width: 5px; height: 5px; margin-left: 1px;
  border-right: 1.5px solid currentColor; border-bottom: 1.5px solid currentColor;
  transform: translateY(-2px) rotate(45deg); }
.langpick > summary:hover { color: #f3ecdd; border-color: rgba(243,236,221,0.3); }
.langpick[open] > summary { color: #f3ecdd; }
.langpick > nav { position: absolute; right: 0; top: calc(100% + 8px); z-index: 60;
  display: grid; min-width: 176px; padding: 6px; border-radius: 12px;
  background: #1b1b21; border: 1px solid rgba(243,236,221,0.14);
  box-shadow: 0 18px 40px rgba(0,0,0,0.45); }
.langpick > nav a { padding: 7px 10px; border-radius: 8px; font-size: 13px;
  color: rgba(243,236,221,0.78); text-decoration: none; white-space: nowrap; }
.langpick > nav a:hover { background: rgba(243,236,221,0.08); color: #f3ecdd; }
.langpick > nav a[aria-current="page"] { color: #f3ecdd; font-weight: 600; }
@media (max-width: 720px) { .langpick > summary span { display: none; } }

.topbar .nav { flex: 1; min-width: 0; display: flex; align-items: center; justify-content: center; gap: 22px; }
.topbar .nav a { font-family: "Geist", -apple-system, system-ui, sans-serif; font-size: 0.9rem;
  color: rgba(243,236,221,0.66); text-decoration: none; transition: color .18s; }
.topbar .nav a:hover { color: #F3ECDD; }
.topbar .nav a.on { color: #D9A066; }

.nav-right { display: flex; align-items: center; gap: 12px; flex: none; }
.nav-github { display: inline-flex; align-items: center; gap: 6px; color: rgba(243,236,221,0.66);
  text-decoration: none; transition: color .18s, transform .18s; }
.nav-github:hover { color: #F3ECDD; transform: scale(1.04); }
.nav-stars { font-family: "Geist Mono", ui-monospace, Menlo, monospace; font-size: 12.5px;
  font-weight: 400; letter-spacing: 0; font-variant-numeric: tabular-nums; }

.icon { fill: currentColor; flex: none; display: block; }
.icon--github { width: 19px; height: 19px; }
.icon--apple { width: 14px; height: 17px; }

.btn { display: inline-flex; align-items: center; justify-content: center; cursor: pointer;
  font-family: "Geist", -apple-system, system-ui, sans-serif; font-size: 0.95rem; font-weight: 600;
  border-radius: 999px; padding: 10px 18px; border: 1px solid #D9A066; background: #D9A066;
  color: #241B12; text-decoration: none; white-space: nowrap;
  transition: background .18s, border-color .18s; }
.btn:hover { background: #E7C49A; border-color: #E7C49A; }
.btn-inner { display: inline-flex; align-items: center; gap: 8px; }
@media (prefers-reduced-motion: no-preference) {
  .btn-inner { transition: transform .18s; }
  .btn:hover .btn-inner { transform: scale(.95); }
}
.btn-sm { padding: 8px 15px; font-size: 0.875rem; }
.btn-lg { padding: 13px 26px; font-size: 1rem; }
.btn-out { background: transparent; color: #F3ECDD; border-color: rgba(243,236,221,0.13); }
.btn-out:hover { background: rgba(243,236,221,0.045); border-color: rgba(243,236,221,0.42); }
.topbar .btn { padding: 8px 15px; font-size: 0.875rem; }

/* platform picker, shared by the install page and the landing page */
.plats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; max-width: 860px; margin: 0 auto; }
.plat { display: flex; flex-direction: column; align-items: center; text-align: center;
  padding: 26px 22px 22px; border-radius: 20px; border: 1px solid rgba(243,236,221,0.13);
  background: rgba(243,236,221,0.045); }
.plat .gl { display: flex; height: 28px; align-items: center; justify-content: center; color: #F3ECDD; }
.plat .gl svg { width: 24px; height: 24px; }
.plat h3 { font-family: "Cal Sans", "Geist", system-ui, sans-serif; font-weight: 600; font-size: 15px;
  letter-spacing: -0.02em; margin: 12px 0 0; color: #F3ECDD; }
.plat .kind { margin: 4px 0 0; font-size: 12px; color: rgba(243,236,221,0.42); }
.plat .tag { display: inline-block; margin-top: 8px; padding: 2px 8px; border-radius: 999px;
  font-family: "Geist Mono", ui-monospace, Menlo, monospace; font-size: 10px; letter-spacing: .04em;
  color: #D9A066; background: rgba(217,160,102,0.14); border: 1px solid rgba(217,160,102,0.26); }
.plat .foot { margin-top: auto; width: 100%; padding-top: 22px; }
.dlbtn { display: flex; width: 100%; align-items: center; justify-content: center; gap: 8px;
  padding: 10px 16px; border-radius: 999px; background: #D9A066; color: #241B12; border: 1px solid #D9A066;
  font-family: "Geist", system-ui, sans-serif; font-size: 13.5px; font-weight: 600; text-decoration: none;
  transition: background .18s, border-color .18s; }
.dlbtn:hover { background: #E7C49A; border-color: #E7C49A; }
.dlbtn svg { width: 13px; height: 13px; stroke: currentColor; fill: none; stroke-width: 2.2; }
.cmdbtn { display: flex; width: 100%; align-items: center; justify-content: space-between; gap: 10px;
  padding: 9px 10px 9px 14px; border-radius: 999px; border: 1px solid rgba(243,236,221,0.13);
  background: rgba(0,0,0,0.28); cursor: pointer; font-family: "Geist Mono", ui-monospace, Menlo, monospace;
  font-size: 11.5px; color: #F3ECDD; transition: border-color .18s; }
.cmdbtn:hover { border-color: rgba(243,236,221,0.42); }
.cmdbtn .lab { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.cmdbtn .st { flex: none; font-size: 10px; color: rgba(243,236,221,0.42); }
.cmdbtn.done .st { color: #57D58E; }
@media (max-width: 760px) { .plats { grid-template-columns: 1fr; max-width: 380px; } }

/* footer, shared by every page */
footer, .footer { margin-top: 8px; border-top: 1px solid rgba(243,236,221,0.075); padding: 34px 0 48px; }
.footer-top { display: flex; align-items: center; justify-content: space-between; gap: 20px;
  flex-wrap: wrap; font-family: "Geist", -apple-system, system-ui, sans-serif;
  font-size: 12.5px; color: rgba(243,236,221,0.42); }
.footer-links { display: flex; align-items: center; gap: 20px; flex-wrap: wrap; }
.footer-links a { color: inherit; text-decoration: none; transition: color .18s; }
.footer-links a:hover { color: #F3ECDD; }

.nav-label--short { display: none; }
@media (max-width: 720px) {
  .topbar .page { padding-left: 12px; padding-right: 12px; }
  .topbar .nav { display: none; }
  .nav-label--full { display: none; }
  .nav-label--short { display: inline; }
}
"""


# --- shared page scaffold -------------------------------------------------

SHARED_CSS = """  @font-face { font-family: "Geist"; src: url("assets/fonts/Geist[wght].woff2") format("woff2"); font-weight: 100 900; font-style: normal; font-display: swap; }
  @font-face { font-family: "Geist Mono"; src: url("assets/fonts/GeistMono[wght].woff2") format("woff2"); font-weight: 100 900; font-style: normal; font-display: swap; }
  @font-face { font-family: "Cal Sans"; src: url("assets/fonts/CalSans-SemiBold.woff2") format("woff2"); font-weight: 600; font-style: normal; font-display: swap; }
  :root {
    --bg:#121217; --surface:rgba(243,236,221,0.045); --surface-2:rgba(243,236,221,0.07);
    --ink:#F3ECDD; --ink-2:rgba(243,236,221,0.72); --ink-3:rgba(243,236,221,0.46);
    --hair:rgba(243,236,221,0.14); --hair-2:rgba(243,236,221,0.08);
    --accent:#D9A066; --on-accent:#241B12; --lilac:#D6C6FF; --apricot:#FFD3B6; --mint:#C9F2E6;
    --teal:#35C2A5; --coral:#F0714E; --violet:#8E84F0; --azure:#4FA3E3;
    --gold:#E6A93C; --moss:#6FB06A; --ginger:#D98C5F; --green:#57D58E; --red:#F0604E;
    --serif:"Geist",-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif;
    --mono:"Geist Mono",ui-monospace,"SF Mono",Menlo,monospace;
    --heading:"Cal Sans","Geist",-apple-system,system-ui,sans-serif;
    --r-card:28px; --page:1080px; --pad:24px;
  }
  * { box-sizing: border-box; }
  html { -webkit-text-size-adjust: 100%; }
  html { height:100%; }
  body { min-height:100%; display:flex; flex-direction:column; }
  /* Flex items with auto cross-axis margins stop stretching and shrink to fit,
     which would let each .page size itself to its own content. Pin them to full
     width so max-width + margin:auto centres them the way block flow would. */
  body > * { width:100%; }
  main { flex:1 0 auto; }
  body { margin:0; color:var(--ink); font-family:var(--serif); font-size:17px; line-height:1.6;
    -webkit-font-smoothing:antialiased; text-rendering:optimizeLegibility; overflow-x:hidden;
    background-color:var(--bg);
    background-image:radial-gradient(1200px 600px at 82% -10%, rgba(217,160,102,0.10), rgba(217,160,102,0) 60%);
    background-repeat:no-repeat; background-attachment:fixed; }
  a { color: inherit; text-decoration: none; }
  ::selection { background: rgba(217,160,102,0.26); }
  .page { max-width: var(--page); margin: 0 auto; padding: 0 var(--pad); }
  .mono { font-family: var(--mono); }
  .hero { padding-top: 72px; padding-bottom: 8px; }
  .hero h1 { font-family:var(--heading); font-weight:600; font-size:clamp(40px,7vw,64px); line-height:1.04;
    letter-spacing:-0.025em; margin:0; }
  .hero p { color:var(--ink-2); margin:14px 0 0; max-width:620px; }
  .hero .count { font-family:var(--mono); font-size:12.5px; color:var(--ink-3); margin-top:12px; }
  .hero .count a { color:var(--ink-2); text-decoration:underline; text-underline-offset:2px; }
  .hero .count a:hover { color:var(--accent); }
  .card { background:var(--surface); border:1px solid var(--hair-2); border-radius:var(--r-card); box-shadow:0 1px 0 rgba(255,255,255,0.05) inset; }
  code { font-family:var(--mono); font-size:0.85em; padding:1px 6px; border-radius:7px; background:var(--surface-2); border:1px solid var(--hair-2); color:var(--ink); white-space:nowrap; }
  main { padding-top: 8px; padding-bottom: 24px; }
  .hero p { max-width:680px; }
  main .entry, main > .rcol { max-width:940px; }
    font-size:12.5px; color:var(--ink-3); }
  .footer-links { display:flex; align-items:center; gap:20px; flex-wrap:wrap; }
  .footer-links a { transition:color .18s; }
  .footer-links a:hover { color:var(--ink); }
  @media (max-width: 720px) { :root { --pad: 20px; } .topbar { padding-left:8px; padding-right:8px; } .nav { display:none; } }
  @media (max-width: 560px) { .nav-label--full { display:none; } }
  @media (min-width: 561px) { .nav-label--short { display:none; } }
"""


def page_html(*, title, desc, og_url, hero_h1, hero_p, hero_extra, main_html,
              extra_css, active, base="", head_extra="", stars=None):
    """Render a full standalone page (topbar + hero + main + footer).

    `base` is the relative prefix back to docs/ ("" at the root, "../" one
    level down), so blog posts can reuse the same chrome and fonts."""
    topbar = render_nav(active, base, stars)
    extra = f'\n  <p class="count">{hero_extra}</p>' if hero_extra else ""
    return f"""<!DOCTYPE html>
<!-- GENERATED by scripts/site-release.py; do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta name="theme-color" content="#121217">
<link rel="icon" type="image/png" href="{base}burrow-icon.png">
<link rel="canonical" href="{og_url}">
{lang_alternates(og_url.removeprefix(SITE + "/"))}
<link rel="stylesheet" href="{base}assets/chrome.css">
<script type="application/ld+json">{ORG_LD}</script>{head_extra}
<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="{SITE}/burrow-icon-512.png">
<meta property="og:url" content="{og_url}">
<meta property="og:site_name" content="Burrow">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<script src="/analytics.js" defer></script>
<style>
{SHARED_CSS.replace(chr(34) + "assets/", chr(34) + base + "assets/")}{extra_css}</style>
</head>
<body>

{topbar}

<header class="hero page">
  <h1>{hero_h1}</h1>
  <p>{hero_p}</p>{extra}
</header>

<main class="page">
{main_html}
</main>

<footer>
  <div class="page">
    <div class="footer-top">
      <a class="brand" href="{base}./" aria-label="Burrow">{logo_img(base)}<span>Burrow</span></a>
      <div class="footer-links">
        <a href="{REPO}" target="_blank" rel="noopener">GitHub</a>
        <a href="{base}blog/">Blog</a>
        <a href="{base}compare">Compare</a>
        <a href="{base}releases">Changelog</a>
        <a href="{base}roadmap">Roadmap</a>
        <a href="{REPO}/blob/main/SECURITY.md" target="_blank" rel="noopener">Security</a>
        <a href="{REPO}/blob/main/TELEMETRY.md" target="_blank" rel="noopener">Telemetry</a>
        <a href="{REPO}/blob/main/LICENSE" target="_blank" rel="noopener">License</a>
      </div>
    </div>
  </div>
</footer>
</body>
</html>
"""


# --- homepage "What's new" + changelog (releases.json) --------------------

def validate(rel):
    # highlights/chips drive the homepage "What's new" cards (latest release).
    for h in rel.get("highlights", []):
        if h["icon"] not in ICONS:
            sys.exit(f"releases.json: unknown icon '{h['icon']}' in {rel['version']} "
                     f"(valid: {', '.join(sorted(ICONS))})")
        if h["color"] not in COLORS:
            sys.exit(f"releases.json: unknown color '{h['color']}' in {rel['version']} "
                     f"(valid: {', '.join(sorted(COLORS))})")
    # sections drive the categorized changelog on releases.html. Free-form
    # label (added/changed/fixed/performance/…); items are markdown strings.
    for s in rel.get("sections", []):
        if not isinstance(s.get("label"), str) or not s["label"].strip():
            sys.exit(f"releases.json: a section needs a non-empty 'label' in {rel['version']}")
        if not isinstance(s.get("items"), list) or not all(isinstance(i, str) for i in s["items"]):
            sys.exit(f"releases.json: section '{s.get('label')}' items must be a list of strings in {rel['version']}")
    date.fromisoformat(rel["date"])  # raises on bad dates


def render_card(h):
    return (f'      <article class="tcard" style="--c: var(--{h["color"]})">\n'
            f'        <div class="top"><div class="ico">{icon_svg(h["icon"])}</div>'
            f'<div class="nm">{esc(h["title"])}</div></div>\n'
            f'        <p class="ds">{md_links(h["line"])}</p>\n'
            f'      </article>')


def render_chip(text, indent="      "):
    return (f'{indent}<span class="wn-chip"><svg viewBox="0 0 24 24" '
            f'stroke-linecap="round" stroke-linejoin="round">{CHECK_PATH}</svg>'
            f'{md_links(text)}</span>')


def render_item(text):
    return f'<li>{md_links(text)}</li>'


def render_section_block(s):
    items = "\n".join(f'            {render_item(it)}' for it in s["items"])
    return (f'        <div class="sblock">\n'
            f'          <div class="slabel mono">{esc(s["label"])}</div>\n'
            f'          <ul class="slist">\n{items}\n          </ul>\n'
            f'        </div>')


def render_whatsnew(rel):
    cards = "\n".join(render_card(h) for h in rel["highlights"])
    chips = "\n".join(render_chip(c) for c in rel["chips"])
    return f"""{WN_BEGIN}
    <div class="sec-head wn-head">
      <div>
        <span class="sec-num">What's new · {month_year(rel["date"])}</span>
        <h2 class="sec-title">New in {esc(rel["version"])}</h2>
      </div>
      <a class="btn btn-out btn-sm" href="releases">All releases</a>
    </div>

    <div class="grid3 wn-grid">
{cards}
    </div>

    <div class="extra-label mono">// also tightened in {esc(rel["version"])}</div>
    <div class="wn-chips">
{chips}
    </div>
    {WN_END}"""


def render_history_entry(rel, latest):
    latest_chip = '<span class="latest">latest</span>' if latest else ""
    lead = f'        <p class="lead">{md_links(rel["tagline"])}</p>\n' if rel.get("tagline") else ""
    if rel.get("sections"):
        body = lead + "\n".join(render_section_block(s) for s in rel["sections"])
        legacy = ""
    else:
        # Fallback for releases not yet migrated to categorized sections.
        hl = "\n".join(
            f'          <div class="hl" style="--c: var(--{h["color"]})">\n'
            f'            <div class="ico">{icon_svg(h["icon"])}</div>\n'
            f'            <div><b>{esc(h["title"])}</b><p>{md_links(h["line"])}</p></div>\n'
            f'          </div>' for h in rel.get("highlights", []))
        chips = "\n".join(render_chip(c, indent="          ") for c in rel.get("chips", []))
        body = (f'{lead}        <div class="hls">\n{hl}\n        </div>\n'
                f'        <div class="wn-chips">\n{chips}\n        </div>')
        legacy = " legacy"
    return f"""    <article class="entry" id="{esc(rel["tag"])}">
      <div class="ver-col">
        <h2 class="ver">{esc(rel["version"])}{latest_chip}</h2>
        <span class="date mono">{pretty_date(rel["date"])}</span>
        <a class="gh mono" href="{REPO}/releases/tag/{esc(rel["tag"])}" target="_blank" rel="noopener">full notes ↗</a>
      </div>
      <div class="sbody{legacy}">
{body}
      </div>
    </article>"""


RELEASES_CSS = """  /* Changelog, a version gutter on the left, categorized changes on the right. */
  .entry { display:grid; grid-template-columns:152px 1fr; gap:32px; padding:38px 0; border-top:1px solid var(--hair-2); }
  .entry:first-child { border-top:none; padding-top:6px; }
  .ver-col { position:sticky; top:84px; align-self:start; }
  .ver { font-family:var(--heading); font-weight:600; font-size:30px; line-height:1; margin:0; display:flex; align-items:center; gap:9px; flex-wrap:wrap; }
  .latest { font-family:var(--mono); font-size:10px; letter-spacing:.04em; padding:3px 9px; border-radius:999px;
    background:rgba(217,160,102,0.16); color:var(--accent); border:1px solid rgba(217,160,102,0.3); }
  .ver-col .date { display:block; margin-top:9px; font-size:12.5px; color:var(--ink-3); }
  .ver-col .gh { display:inline-block; margin-top:12px; font-size:12px; color:var(--ink-2); }
  .ver-col .gh:hover { color:var(--accent); }
  .lead { margin:0; font-size:15.5px; color:var(--ink-2); }
  .sblock { margin-top:24px; }
  .sbody > .sblock:first-child { margin-top:0; }
  .slabel { font-size:11px; letter-spacing:.12em; color:var(--accent); text-transform:lowercase; margin-bottom:11px; }
  .slist { list-style:none; margin:0; padding:0; display:grid; gap:11px; }
  .slist > li { position:relative; padding-left:18px; font-size:14.5px; line-height:1.55; color:var(--ink); }
  .slist > li::before { content:""; position:absolute; left:1px; top:8px; width:5px; height:5px; border-radius:50%;
    background:color-mix(in srgb, var(--accent) 75%, transparent); }
  .slist b { font-weight:600; }
  .slist a { color:var(--accent); text-decoration:underline; text-underline-offset:2px; }
  .slist .req { color:var(--ink-3); }
  /* Legacy card style, fallback for releases not yet migrated to sections. */
  .sbody.legacy .hls { margin-top:16px; display:grid; grid-template-columns:1fr 1fr; gap:14px 22px; }
  .hl { display:flex; gap:12px; align-items:flex-start; }
  .hl .ico { width:32px; height:32px; border-radius:10px; display:grid; place-items:center; flex:0 0 auto; margin-top:2px;
    background:color-mix(in srgb, var(--c) 16%, transparent); border:1px solid color-mix(in srgb, var(--c) 36%, transparent); }
  .hl .ico svg { width:17px; height:17px; stroke:var(--c); fill:none; stroke-width:1.8; }
  .hl b { font-size:15px; }
  .hl p { margin:3px 0 0; font-size:13.5px; line-height:1.5; color:var(--ink-2); }
  .hl p a { color:var(--accent); text-decoration:underline; text-underline-offset:2px; }
  .wn-chips { margin-top:18px; display:flex; flex-wrap:wrap; gap:9px; }
  .wn-chip { display:inline-flex; align-items:center; gap:8px; font-family:var(--mono); font-size:12px; color:var(--ink-2);
    border:1px solid var(--hair-2); background:var(--surface); border-radius:999px; padding:7px 13px; }
  .wn-chip svg { width:12px; height:12px; stroke:var(--green); fill:none; stroke-width:2.4; flex:0 0 auto; }
  .wn-chip a { color:var(--accent); text-decoration:underline; text-underline-offset:2px; }
  @media (max-width: 720px) {
    .entry { grid-template-columns:1fr; gap:12px; padding:28px 0; }
    .ver-col { position:static; }
    .sbody.legacy .hls { grid-template-columns:1fr; }
  }
"""


def render_history(releases, stars=None):
    entries = "\n\n".join(render_history_entry(r, i == 0)
                          for i, r in enumerate(releases))
    latest = releases[0]
    count = (f'{len(releases)} releases · latest {esc(latest["version"])} · '
             f'<a href="{REPO}/releases" target="_blank" rel="noopener">GitHub releases ↗</a>')
    return page_html(
        title="Burrow · Changelog",
        desc="Every Burrow release at a glance, what each version added, fixed, and tightened.",
        og_url=f"{SITE}/releases",
        hero_h1="Changelog",
        hero_p="Every version at a glance, what it added, changed, and fixed. Full notes for each live on GitHub.",
        hero_extra=count,
        main_html=entries,
        extra_css=RELEASES_CSS,
        active="changelog", stars=stars,
    )


# --- roadmap (roadmap.json) ----------------------------------------------

ROADMAP_CSS = """  /* Roadmap, status sections of feature cards. */
  .rcol { padding:30px 0; border-top:1px solid var(--hair-2); }
  .rcol:first-child { border-top:none; padding-top:10px; }
  .rcol-head { display:flex; align-items:baseline; gap:10px; flex-wrap:wrap; }
  .rcol-head h2 { font-family:var(--heading); font-weight:600; font-size:22px; margin:0; }
  .rcol-head .ct { font-family:var(--mono); font-size:12px; color:var(--ink-3); }
  .rcol-head .blurb { margin-left:auto; font-size:13px; color:var(--ink-3); }
  .ritems { margin-top:16px; display:grid; grid-template-columns:1fr 1fr; gap:12px; }
  .ritem { background:var(--surface); border:1px solid var(--hair-2); border-radius:16px; padding:14px 16px; display:flex; flex-direction:column; gap:7px; }
  .ritem .t { font-size:14.5px; line-height:1.45; }
  .ritem .note { margin:0; font-size:13px; color:var(--ink-2); line-height:1.5; }
  .rtags { display:flex; align-items:center; gap:8px; margin-top:auto; padding-top:3px; }
  .rtype { font-family:var(--mono); font-size:10px; letter-spacing:.04em; text-transform:uppercase; padding:2px 8px; border-radius:999px; border:1px solid var(--hair); color:var(--ink-2); }
  .rtype.feat { color:var(--teal); border-color:color-mix(in srgb, var(--teal) 40%, transparent); }
  .rtype.fix { color:var(--coral); border-color:color-mix(in srgb, var(--coral) 40%, transparent); }
  .rtype.infra { color:var(--azure); border-color:color-mix(in srgb, var(--azure) 40%, transparent); }
  .rissue { font-family:var(--mono); font-size:11.5px; color:var(--ink-2); text-decoration:underline; text-underline-offset:2px; }
  .rissue:hover { color:var(--accent); }
  .rver { font-family:var(--mono); font-size:11px; color:var(--accent); border:1px solid rgba(217,160,102,0.3);
    background:rgba(217,160,102,0.12); padding:2px 8px; border-radius:999px; }
  @media (max-width: 720px) { .ritems { grid-template-columns:1fr; } .rcol-head .blurb { display:none; } }
"""


def validate_roadmap(data):
    date.fromisoformat(data["updated"])
    for col in data.get("columns", []):
        if not col.get("title"):
            sys.exit("roadmap.json: a column needs a 'title'")
        for it in col.get("items", []):
            if not isinstance(it.get("title"), str) or not it["title"].strip():
                sys.exit(f"roadmap.json: an item in '{col['title']}' needs a 'title'")
            if it.get("type") and it["type"] not in RTYPES:
                sys.exit(f"roadmap.json: unknown type '{it['type']}' in '{col['title']}' "
                         f"(valid: {', '.join(sorted(RTYPES))})")


def render_roadmap_item(it):
    note = f'\n          <p class="note">{md_links(it["note"])}</p>' if it.get("note") else ""
    tags = []
    if it.get("type"):
        tags.append(f'<span class="rtype {esc(it["type"])}">{esc(it["type"])}</span>')
    if it.get("issue"):
        n = int(it["issue"])
        tags.append(f'<a class="rissue" href="{REPO}/issues/{n}" target="_blank" rel="noopener">#{n} ↗</a>')
    if it.get("version"):
        v = esc(it["version"])
        tags.append(f'<a class="rver" href="releases.html#v{v}">{v}</a>')
    tags_html = f'\n          <div class="rtags">{"".join(tags)}</div>' if tags else ""
    return (f'        <div class="ritem">\n'
            f'          <span class="t">{md_links(it["title"])}</span>{note}{tags_html}\n'
            f'        </div>')


def render_roadmap(data, stars=None):
    cols = []
    for col in data["columns"]:
        items = col.get("items", [])
        if not items:
            continue
        cards = "\n".join(render_roadmap_item(it) for it in items)
        blurb = f'<span class="blurb">{esc(col["blurb"])}</span>' if col.get("blurb") else ""
        cols.append(
            f'    <section class="rcol">\n'
            f'      <div class="rcol-head"><h2>{esc(col["title"])}</h2>'
            f'<span class="ct">{len(items)}</span>{blurb}</div>\n'
            f'      <div class="ritems">\n{cards}\n      </div>\n'
            f'    </section>')
    cta = (f'A guide, not a promise, order shifts with what people ask for. '
           f'Upvote an issue to push it up, or '
           f'<a href="{REPO}/issues/new/choose" target="_blank" rel="noopener">open a request ↗</a>. '
           f'Updated {pretty_date(data["updated"])}.')
    return page_html(
        title="Burrow · Roadmap",
        desc="What's shipped, building, and being weighed for Burrow, and how to vote.",
        og_url=f"{SITE}/roadmap",
        hero_h1="Roadmap",
        hero_p="What's shipped, what's being built, and what we're weighing next.",
        hero_extra=cta,
        main_html="\n".join(cols),
        extra_css=ROADMAP_CSS,
        active="roadmap", stars=stars,
    )


def render_readme_roadmap(data):
    """The README "## Roadmap" block, GitHub markdown, raw (not HTML)."""
    out = [RM_BEGIN,
           f"The full board, with status and voting, lives at "
           f"**[{SITE_HOST}/roadmap]({SITE}/roadmap)**. Vote by upvoting an "
           f"issue, or [open a request]({REPO}/issues/new/choose).", ""]
    for col in data["columns"]:
        items = col.get("items", [])
        if not items or col.get("key") == "shipped":
            continue
        out.append(f"**{col['title']}**")
        out.append("")
        for it in items:
            ref = f" ([#{int(it['issue'])}]({REPO}/issues/{int(it['issue'])}))" if it.get("issue") else ""
            note = f", {it['note']}" if it.get("note") else ""
            out.append(f"- {it['title']}{note}{ref}")
        out.append("")
    shipped = next((c for c in data["columns"] if c.get("key") == "shipped"), None)
    if shipped and shipped.get("items"):
        names = ", ".join(i["title"] for i in shipped["items"][:5])
        out.append(f"_Recently shipped: {names}, see the [changelog]({SITE}/releases.html)._")
    out.append(RM_END)
    return "\n".join(out)


# --- patchers + main ------------------------------------------------------

# --- hero download count (GitHub release assets) --------------------------

def gh_json(path):
    """GET one GitHub API path. Raises on any failure; callers decide."""
    import urllib.request
    req = urllib.request.Request(
        f"https://api.github.com/{path}",
        headers={"Accept": "application/vnd.github+json",
                 "User-Agent": "burrow-site-release"})
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.loads(r.read().decode("utf-8"))


def fetch_stars():
    """Stargazer count, or None when GitHub isn't reachable."""
    try:
        return gh_json("repos/caezium/Burrow")["stargazers_count"]
    except Exception as e:                                  # noqa: BLE001
        print(f"star count: skipped ({e})", file=sys.stderr)
        return None


def compact(n):
    """1234 -> 1.2k, matching how repo badges render large counts."""
    if n < 1000:
        return str(n)
    if n < 10000:
        return f"{n / 1000:.1f}k".replace(".0k", "k")
    return f"{round(n / 1000)}k"


def fetch_download_total():
    """Sum every release asset's download count. None when GitHub isn't
    reachable, the caller then leaves the existing number alone."""
    total, page = 0, 1
    try:
        while True:
            batch = gh_json(f"repos/caezium/Burrow/releases?per_page=100&page={page}")
            if not batch:
                break
            for release in batch:
                for asset in release.get("assets", []):
                    total += asset.get("download_count", 0)
            if len(batch) < 100:
                break
            page += 1
    except Exception as e:                                  # noqa: BLE001
        print(f"download count: skipped ({e})", file=sys.stderr)
        return None
    return total


def render_downloads(total):
    return (f'{DL_BEGIN}\n'
            f'    <p class="dl-line reveal d4">Already downloaded by '
            f'<b>{total:,}</b> people</p>\n'
            f'    {DL_END}')


def patch_index(html, rel, stats):
    begin = html.find(WN_BEGIN)
    end = html.find(WN_END)
    if begin == -1 or end == -1:
        sys.exit("index.html: WN:BEGIN / WN:END markers not found")
    html = html[:begin] + render_whatsnew(rel) + html[end + len(WN_END):]
    # Hero version badge.
    html = re.sub(r'(<span id="hero-version">)v[0-9][^<]*',
                  rf"\g<1>v{rel['version']}", html)
    # Counts come from docs/stats.json so every run is deterministic; only
    # --stats goes to the network and rewrites that file.
    begin, end = html.find(DL_BEGIN), html.find(DL_END)
    if begin == -1 or end == -1:
        sys.exit("index.html: DL:BEGIN / DL:END markers not found")
    html = html[:begin] + render_downloads(stats["downloads"]) + html[end + len(DL_END):]

    begin, end = html.find(PICK_BEGIN), html.find(PICK_END)
    if begin == -1 or end == -1:
        sys.exit("index.html: PICK:BEGIN / PICK:END markers not found")
    picker = render_platforms(rel["version"], "landing")
    html = html[:begin] + f"{PICK_BEGIN}\n{picker}\n      {PICK_END}" + html[end + len(PICK_END):]

    begin, end = html.find(NAV_BEGIN), html.find(NAV_END)
    if begin == -1 or end == -1:
        sys.exit("index.html: NAV:BEGIN / NAV:END markers not found")
    nav = render_nav("home", "", stats["stars"])
    html = html[:begin] + f"{NAV_BEGIN}\n{nav}\n{NAV_END}" + html[end + len(NAV_END):]
    return html


def patch_readme(text, data):
    begin = text.find(RM_BEGIN)
    end = text.find(RM_END)
    if begin == -1 or end == -1:
        sys.exit("README.md: ROADMAP:BEGIN / ROADMAP:END markers not found")
    return text[:begin] + render_readme_roadmap(data) + text[end + len(RM_END):]


# --- install page ---------------------------------------------------------

INSTALL_CSS = """  /* Centered platform picker; the cards themselves come from chrome.css. */
  .hero { text-align:center; padding-top:72px; padding-bottom:0; }
  .hero h1 { margin:0 auto; }
  .hero p { margin-left:auto; margin-right:auto; max-width:34rem; }
  main { padding-bottom:72px; }
  .pick { margin-top:52px; }
  .pick > .lede { font-size:12.5px; color:var(--ink-3); margin:0 0 22px; text-align:center; }
  .dlcount { margin-top:34px; text-align:center; font-size:12.5px; color:var(--ink-3); }
  .dlcount b { font-weight:600; color:var(--ink-2); font-variant-numeric:tabular-nums; }
  .rel { margin-top:9px; text-align:center; font-size:12.5px; line-height:1.6; color:var(--ink-3); }
  .rel a { color:var(--accent); text-decoration:underline; text-underline-offset:2px; }
"""

MAC_SIZE = "22 MB"
WIN_VERSION = "0.10.0"

ARROW = ('<svg viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" '
         'aria-hidden="true"><path d="M12 3v12M7 11l5 5 5-5M5 21h14"/></svg>')

GLYPHS = {
    "mac": ('<svg viewBox="0 0 814 1000" fill="currentColor" aria-hidden="true"><path d="M788.1 340.9c-5.8 4.5-108.2 '
            '62.2-108.2 190.5 0 148.4 130.3 200.9 134.2 202.2-.6 3.2-20.7 71.9-68.7 141.9-42.8 61.6-87.5 123.1-155.5 '
            '123.1s-85.5-39.5-164-39.5c-76.5 0-103.7 40.8-165.9 40.8s-105.6-57-155.5-127C46.7 790.7 0 663 0 541.8c0-194.4 '
            '126.4-297.5 250.8-297.5 66.1 0 121.2 43.4 162.7 43.4 39.5 0 101.1-46 176.3-46 28.2 0 129.8 2.6 196.3 '
            '99.2zm-234-181.1c31.1-36.9 53.1-88.1 53.1-139.3 0-7.1-.6-14.3-1.9-20.1-50.6 1.9-110.8 33.7-147.1 75.8-28.2 '
            '32.4-54.4 84.4-54.4 136.5 0 7.8 1.3 15.6 1.9 18.1 3.2.6 8.4 1.3 13.6 1.3 45.4 0 102.5-30.4 135.8-71.3z"/></svg>'),
    "win": ('<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M3 5.5l7.5-1v7.2H3zM11.8 4.3'
            'L21 3v8.7h-9.2zM3 12.9h7.5v7.2L3 18.8zM11.8 12.9H21V21l-9.2-1.3z"/></svg>'),
    "brew": ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" '
             'stroke-linejoin="round" aria-hidden="true"><path d="M5 8h11v7a5 5 0 01-5 5H10a5 5 0 01-5-5z"/>'
             '<path d="M16 10h1.5a2.5 2.5 0 010 5H16"/><path d="M7 4.5c0-.8.6-1.2.6-2M11 4.5c0-.8.6-1.2.6-2"/></svg>'),
}

INSTALL_JS = """
<script>
  document.querySelectorAll('.cmdbtn').forEach(function (btn) {
    btn.addEventListener('click', function () {
      if (navigator.clipboard) navigator.clipboard.writeText(btn.getAttribute('data-copy') || '').catch(function () {});
      var st = btn.querySelector('.st'); btn.classList.add('done'); st.textContent = 'copied';
      setTimeout(function () { btn.classList.remove('done'); st.textContent = 'copy'; }, 1500);
    });
  });
</script>"""


def render_platforms(version, where):
    """The three platform cards. Used by both the install page and the
    landing page's install section, so the two cannot drift apart."""
    brew = "brew install --cask caezium/tap/burrow"
    return f"""      <div class="plats">
        <div class="plat">
          <span class="gl">{GLYPHS["mac"]}</span>
          <h3>macOS</h3>
          <p class="kind">.zip &middot; Apple Silicon &amp; Intel</p>
          <div class="foot">
            <a class="dlbtn" href="{REPO}/releases/download/v{version}/Burrow-{version}.zip" data-burrow-analytics="download.{where}_mac">Download {ARROW}</a>
          </div>
        </div>
        <div class="plat">
          <span class="gl">{GLYPHS["win"]}</span>
          <h3>Windows</h3>
          <p class="kind">.zip &middot; 64-bit</p>
          <span class="tag">beta &middot; {WIN_VERSION}</span>
          <div class="foot">
            <a class="dlbtn" href="{REPO}/releases/download/v{WIN_VERSION}/BurrowWin-{WIN_VERSION}-win-x64.zip" data-burrow-analytics="download.{where}_windows">Download {ARROW}</a>
          </div>
        </div>
        <div class="plat">
          <span class="gl">{GLYPHS["brew"]}</span>
          <h3>Homebrew</h3>
          <p class="kind">cask &middot; app + engine</p>
          <div class="foot">
            <button type="button" class="cmdbtn" data-copy="{brew}" data-burrow-analytics="homebrew.{where}" aria-label="copy the Homebrew install command"><span class="lab">{brew}</span><span class="st">copy</span></button>
          </div>
        </div>
      </div>"""


def render_install(version, downloads, stars=None):
    brew = "brew install --cask caezium/tap/burrow"
    body = f"""    <div class="pick">
      <p class="lede">Pick your platform to download the latest build.</p>
{render_platforms(version, "install")}
      <p class="dlcount">Already downloaded by <b>{downloads:,}</b> people</p>
      <p class="rel">Latest release v{version}, a {MAC_SIZE} universal build.
        Looking for an older version, the Windows preview notes, or the checksums?
        <a href="{REPO}/releases" target="_blank" rel="noopener">Browse all releases</a>.<br>
        Prefer to compile it yourself? The <a href="{REPO}#readme" target="_blank" rel="noopener">README</a> has the build steps.</p>
    </div>
{INSTALL_JS}"""
    return page_html(
        title="Download Burrow",
        desc="Download Burrow for macOS or Windows, or install it with Homebrew. Free, MIT licensed, no account and no subscription.",
        og_url=f"{SITE}/install", hero_h1="Download Burrow",
        hero_p="Get the app for your machine. Free, native, and open source, on as many machines as you like.",
        hero_extra="", main_html=body, extra_css=INSTALL_CSS, active="install", stars=stars,
        head_extra=f'\n<script type="application/ld+json">{SOFTWARE_LD}</script>')


# --- comparison page ------------------------------------------------------

COMPARE_CSS = """  .cmp-note { max-width:70ch; font-size:14.5px; line-height:1.65; color:var(--ink-2); margin-top:4px; }
  .cmp-scroll { margin-top:34px; overflow-x:auto; }
  table.cmp { border-collapse:collapse; width:100%; min-width:720px; font-size:13.5px; }
  table.cmp th, table.cmp td { text-align:center; padding:12px 10px; border-bottom:1px solid var(--hair-2); }
  table.cmp th:first-child, table.cmp td:first-child { text-align:left; width:38%; }
  table.cmp thead th { position:sticky; top:0; background:rgba(18,18,23,0.94);
    backdrop-filter:blur(8px); -webkit-backdrop-filter:blur(8px); font-weight:600; font-size:13.5px; z-index:5; }
  table.cmp thead th .n { display:block; font-family:var(--mono); font-size:10.5px; color:var(--ink-3);
    margin-top:3px; font-weight:400; }
  table.cmp th.self { color:var(--accent); }
  .grp td { padding-top:26px; font-family:var(--mono); font-size:11px; letter-spacing:.12em; text-transform:uppercase;
    color:var(--accent); border-bottom:1px solid var(--hair); }
  .lbl b { font-weight:500; color:var(--ink); }
  .lbl span { display:block; font-size:12px; color:var(--ink-3); margin-top:3px; line-height:1.45; }
  .mk { display:inline-block; font-size:15px; line-height:1; }
  .mk.y { color:var(--green); }
  .mk.p { color:var(--gold); }
  .mk.n { color:var(--ink-3); opacity:.5; }
  td.txt { font-family:var(--mono); font-size:12.5px; }
  .cmp-close { margin-top:32px; max-width:70ch; font-size:14.5px; line-height:1.65; color:var(--ink-2); }
"""

MARKS = {"yes": ("y", "&#10003;"), "partial": ("p", "&#8210;"), "no": ("n", "&#215;")}


def render_compare(data, stars=None):
    cols = data["columns"]
    head = "".join(
        '<th class="self">' if c.get("self") else "<th>"
        for c in cols)
    head = "".join(
        (f'<th class="self">' if c.get("self") else "<th>")
        + f'{esc(c["name"])}<span class="n">{esc(c["note"])}</span></th>'
        for c in cols)
    rows = []
    for g in data["groups"]:
        rows.append(f'      <tr class="grp"><td colspan="{len(cols) + 1}">{esc(g["title"])}</td></tr>')
        for r in g["rows"]:
            note = f'<span>{esc(r["note"])}</span>' if r.get("note") else ""
            cells = []
            for c in cols:
                v = r.get(c["key"], "no")
                if r.get("text"):
                    cells.append(f'<td class="txt">{esc(v)}</td>')
                else:
                    cls, ch = MARKS.get(v, MARKS["no"])
                    cells.append(f'<td><span class="mk {cls}" title="{v}">{ch}</span></td>')
            rows.append(f'      <tr><td class="lbl"><b>{esc(r["label"])}</b>{note}</td>{"".join(cells)}</tr>')
    joined = "\n".join(rows)
    body = (f'    <p class="cmp-note">{esc(data["intro"])}</p>\n'
            f'    <div class="cmp-scroll">\n    <table class="cmp">\n'
            f'      <thead><tr><th></th>{head}</tr></thead>\n      <tbody>\n'
            f'{joined}\n      </tbody>\n    </table>\n    </div>\n'
            f'    <p class="cmp-close">{esc(data["closing"])}</p>')
    return page_html(
        title="Burrow compared to CleanMyMac, Pearcleaner, DaisyDisk, and iStat Menus",
        desc="A feature-by-feature comparison of Burrow against the Mac cleanup, uninstall, disk analysis, and monitoring tools it overlaps with.",
        og_url=f"{SITE}/compare", hero_h1="How Burrow compares",
        hero_p="One window against four specialists. Where each one wins, and where Burrow does not.",
        hero_extra="", main_html=body, extra_css=COMPARE_CSS, active="compare", stars=stars,
        head_extra=f'\n<script type="application/ld+json">{SOFTWARE_LD}</script>')


# --- blog -----------------------------------------------------------------

BLOG_CSS = """  .post-list { margin-top:14px; }
  .post-row { display:block; padding:26px 0; border-bottom:1px solid var(--hair-2); }
  .post-row:first-child { border-top:1px solid var(--hair-2); }
  .post-row h2 { font-family:var(--heading); font-weight:600; font-size:21px; letter-spacing:-0.025em; margin:0;
    transition:color .18s; }
  .post-row:hover h2 { color:var(--accent); }
  .post-row p { margin:9px 0 0; font-size:14.5px; line-height:1.6; color:var(--ink-2); max-width:70ch; }
  .post-meta { margin-top:11px; font-family:var(--mono); font-size:11.5px; color:var(--ink-3);
    display:flex; gap:10px; flex-wrap:wrap; }
  .post-meta .cat { color:var(--accent); }
  article.post { max-width:70ch; }
  article.post h2 { font-family:var(--heading); font-weight:600; font-size:24px; letter-spacing:-0.025em;
    margin:38px 0 0; line-height:1.2; }
  article.post p { margin:16px 0 0; font-size:16px; line-height:1.72; color:var(--ink-2); }
  article.post ul { margin:16px 0 0; padding:0; list-style:none; display:grid; gap:11px; }
  article.post ul li { position:relative; padding-left:19px; font-size:15.5px; line-height:1.65; color:var(--ink-2); }
  article.post ul li::before { content:""; position:absolute; left:1px; top:9px; width:5px; height:5px;
    border-radius:50%; background:color-mix(in srgb, var(--accent) 75%, transparent); }
  article.post pre { margin:18px 0 0; padding:15px 17px; border-radius:12px; background:rgba(0,0,0,0.32);
    border:1px solid var(--hair-2); font-family:var(--mono); font-size:13px; line-height:1.7; color:var(--ink);
    overflow-x:auto; }
  article.post pre code { background:none; border:0; padding:0; font-size:inherit; white-space:pre; }
  article.post .cta { margin:34px 0 0; padding:20px 22px; border-radius:16px; background:var(--surface);
    border:1px solid var(--hair-2); font-size:14.5px; line-height:1.6; color:var(--ink-2); }
  article.post .cta a { color:var(--accent); text-decoration:underline; text-underline-offset:2px; }
  .post-foot { margin-top:44px; padding-top:26px; border-top:1px solid var(--hair-2); font-size:14px; }
  .post-foot a { color:var(--accent); text-decoration:underline; text-underline-offset:2px; }
  .more { margin-top:40px; padding-top:26px; border-top:1px solid var(--hair-2); }
  .more h3 { font-family:var(--mono); font-size:11px; letter-spacing:.12em; text-transform:uppercase;
    color:var(--ink-3); margin:0 0 10px; font-weight:400; }
  .more a { display:block; padding:11px 0; font-size:15px; color:var(--ink);
    border-bottom:1px solid var(--hair-2); transition:color .18s; }
  .more a:hover { color:var(--accent); }
"""


def slugify(t):
    return re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-")


def blog_block(b):
    if "h3" in b:
        return f'      <h3 id="{slugify(b["h3"])}">{esc(b["h3"])}</h3>'
    if "h2" in b:
        return f'      <h2>{esc(b["h2"])}</h2>'
    if "p" in b:
        return f'      <p>{md_links(b["p"])}</p>'
    if "ul" in b:
        items = "\n".join(f'        <li>{md_links(i)}</li>' for i in b["ul"])
        return f'      <ul>\n{items}\n      </ul>'
    if "code" in b:
        return f'      <pre><code>{esc(b["code"])}</code></pre>'
    if "note" in b:
        return f'      <div class="cta">{md_links(b["note"])}</div>'
    if "link" in b:
        return f'      <p><a href="../{esc(b["link"]["href"]).replace(".html","")}">{esc(b["link"]["text"])}</a></p>'
    return ""


def post_url(post):
    return f'{SITE}/blog/{post["slug"]}'


def render_blog_post(post, cats, others, stars=None):
    body = "\n".join(blog_block(b) for b in post["body"])
    rel = [p for p in others if p["slug"] != post["slug"]][:4]
    more = "\n".join(f'    <a href="{p["slug"]}">{esc(p["title"])}</a>' for p in rel)
    ld = json.dumps({
        "@context": "https://schema.org", "@type": "Article",
        "headline": post["title"], "description": post["description"],
        "datePublished": post["date"], "dateModified": post["date"],
        "author": {"@type": "Organization", "name": "Burrow"},
        "publisher": {"@type": "Organization", "name": "Burrow"},
        "mainEntityOfPage": post_url(post),
    }, separators=(",", ":"))
    main = (f'    <article class="post">\n{body}\n    </article>\n'
            f'    <p class="post-foot"><a href="./">All posts</a></p>\n'
            f'    <div class="more"><h3>More reading</h3>\n{more}\n    </div>')
    meta = f'{cats[post["category"]]} · {pretty_date(post["date"])} · {post["read"]} read'
    return page_html(
        title=post["title"], desc=post["description"], og_url=post_url(post),
        hero_h1=post["title"], hero_p=post["description"], hero_extra=meta,
        main_html=main, extra_css=BLOG_CSS, active="blog", base="../", stars=stars,
        head_extra=f'\n<script type="application/ld+json">{ld}</script>')


def render_blog_index(data, stars=None):
    cats = data["categories"]
    posts = sorted(data["posts"], key=lambda p: p["date"], reverse=True)
    rows = []
    for p in posts:
        rows.append(
            f'      <a class="post-row" href="{p["slug"]}">\n'
            f'        <h2>{esc(p["title"])}</h2>\n'
            f'        <p>{esc(p["description"])}</p>\n'
            f'        <div class="post-meta"><span class="cat">{esc(cats[p["category"]])}</span>'
            f'<span>{pretty_date(p["date"])}</span><span>{esc(p["read"])} read</span></div>\n'
            f'      </a>')
    ld = json.dumps({
        "@context": "https://schema.org", "@type": "Blog",
        "name": "Burrow Blog", "url": f"{SITE}/blog/",
        "blogPost": [{"@type": "BlogPosting", "headline": p["title"],
                      "url": post_url(p), "datePublished": p["date"]} for p in posts],
    }, separators=(",", ":"))
    joined = "\n".join(rows)
    return page_html(
        title="Burrow Blog", desc=data["intro"], og_url=f"{SITE}/blog/",
        hero_h1="Blog", hero_p=data["intro"], hero_extra=f"{len(posts)} posts",
        main_html=f'    <div class="post-list">\n{joined}\n    </div>',
        extra_css=BLOG_CSS, active="blog", base="../", stars=stars,
        head_extra=f'\n<script type="application/ld+json">{ld}</script>')


DOCS_CSS = """  .dwrap { display:grid; grid-template-columns:210px 1fr; gap:56px; align-items:start; }
  .dtoc { position:sticky; top:96px; align-self:start; font-size:13px; }
  .dtoc h2 { font-family:var(--mono); font-size:10.5px; letter-spacing:.14em; text-transform:uppercase;
    color:var(--ink-3); margin:0 0 12px; font-weight:400; }
  .dtoc a { display:block; padding:6px 0; color:var(--ink-2); border-left:1px solid var(--hair-2);
    padding-left:12px; transition:color .18s, border-color .18s; }
  .dtoc a:hover { color:var(--accent); border-color:var(--accent); }
  .dbody { min-width:0; max-width:74ch; }
  .dsec { padding-bottom:14px; }
  .dsec + .dsec { margin-top:44px; padding-top:38px; border-top:1px solid var(--hair-2); }
  .dsec > h2 { font-family:var(--heading); font-weight:600; font-size:26px; letter-spacing:-0.025em;
    margin:0; line-height:1.15; }
  .dsec h3 { font-family:var(--heading); font-weight:600; font-size:17px; letter-spacing:-0.02em;
    margin:30px 0 0; color:var(--ink); }
  .dsec p { margin:13px 0 0; font-size:15px; line-height:1.72; color:var(--ink-2); }
  .dsec ul { margin:14px 0 0; padding:0; list-style:none; display:grid; gap:10px; }
  .dsec ul li { position:relative; padding-left:19px; font-size:15px; line-height:1.65; color:var(--ink-2); }
  .dsec ul li::before { content:""; position:absolute; left:1px; top:9px; width:5px; height:5px;
    border-radius:50%; background:color-mix(in srgb, var(--accent) 75%, transparent); }
  .dsec pre { margin:16px 0 0; padding:15px 17px; border-radius:12px; background:rgba(0,0,0,0.32);
    border:1px solid var(--hair-2); font-family:var(--mono); font-size:12.5px; line-height:1.7;
    color:var(--ink); overflow-x:auto; }
  .dsec pre code { background:none; border:0; padding:0; font-size:inherit; white-space:pre; }
  .dsec .cta { margin:20px 0 0; padding:16px 18px; border-radius:14px; background:var(--surface);
    border:1px solid var(--hair-2); font-size:14px; line-height:1.6; color:var(--ink-2); }
  .dsec a { color:var(--accent); text-decoration:underline; text-underline-offset:2px; }
  @media (max-width:900px) { .dwrap { grid-template-columns:1fr; gap:26px; } .dtoc { position:static; } }
"""


ORG_LD = json.dumps({
    "@context": "https://schema.org",
    "@graph": [
        {"@type": "Organization", "@id": f"{SITE}/#org", "name": "Burrow",
         "url": SITE, "logo": f"{SITE}/burrow-icon-512.png",
         "sameAs": ["https://github.com/caezium/Burrow"]},
        {"@type": "WebSite", "@id": f"{SITE}/#site", "url": SITE, "name": "Burrow",
         "publisher": {"@id": f"{SITE}/#org"}},
    ],
}, separators=(",", ":"))

SOFTWARE_LD = json.dumps({
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "Burrow",
    "applicationCategory": "UtilitiesApplication",
    "operatingSystem": "macOS 14+, Windows 10/11",
    "description": ("A free, open-source desktop utility that clears junk, finds duplicate and "
                    "leftover files, maps disk usage, and watches live system status, with an "
                    "MCP server so coding agents can read the machine."),
    "url": SITE,
    "downloadUrl": f"{SITE}/install",
    "license": "https://github.com/caezium/Burrow/blob/main/LICENSE",
    "isAccessibleForFree": True,
    "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
}, separators=(",", ":"))


def render_docs(data, stars=None):
    toc, secs = [], []
    for sec in data["sections"]:
        toc.append(f'      <a href="#{sec["id"]}">{esc(sec["title"])}</a>')
        blocks = "\n".join(blog_block(b) for b in sec["body"])
        secs.append(f'    <section class="dsec" id="{sec["id"]}">\n'
                    f'      <h2>{esc(sec["title"])}</h2>\n{blocks}\n    </section>')
    nav = "\n".join(toc)
    body = "\n".join(secs)
    return page_html(
        title="Burrow Documentation",
        desc="What every Burrow tool does, what it touches, the safety rules it follows, and how to connect it to a coding agent over MCP.",
        og_url=f"{SITE}/docs", hero_h1="Documentation",
        hero_p=data["intro"], hero_extra="",
        main_html=(f'  <div class="dwrap">\n    <nav class="dtoc">\n      <h2>Contents</h2>\n'
                   f'{nav}\n    </nav>\n    <div class="dbody">\n{body}\n    </div>\n  </div>'),
        extra_css=DOCS_CSS, active="docs", stars=stars,
        head_extra=f'\n<script type="application/ld+json">{SOFTWARE_LD}</script>')


def render_robots():
    return ("User-agent: *\n"
            "Allow: /\n"
            "\n"
            "# Answer engines and AI crawlers are welcome; the content is the point.\n"
            "User-agent: GPTBot\n"
            "Allow: /\n"
            "\n"
            "User-agent: ClaudeBot\n"
            "Allow: /\n"
            "\n"
            "User-agent: PerplexityBot\n"
            "Allow: /\n"
            "\n"
            f"Sitemap: {SITE}/sitemap.xml\n")


def breadcrumb_ld(trail):
    """trail: [(name, url), ...] ending at the current page."""
    return json.dumps({
        "@context": "https://schema.org", "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": u}
            for i, (n, u) in enumerate(trail)
        ],
    }, separators=(",", ":"))


# Languages the site is published in. scripts/site-i18n.py renders the copies
# under docs/<lang>/; this script owns the English pages, so it renders their
# picker and alternates itself. Keep the two lists in step — docs/localization.md.
SITE_LANGUAGES = {
    "zh-Hans": "简体中文", "zh-Hant": "繁體中文", "ru": "Русский",
    "ja": "日本語", "de": "Deutsch", "fr": "Français",
    "es": "Español", "ko": "한국어", "pt-BR": "Português (Brasil)",
}


def lang_picker(page_path):
    """The English page's language menu, marked so site-i18n.py can swap it."""
    items = [f'<a href="/{page_path}" hreflang="en" aria-current="page">English</a>']
    items += [f'<a href="/{code}/{page_path}" hreflang="{code}">{name}</a>'
              for code, name in SITE_LANGUAGES.items()]
    return ('<!-- LANGPICK:BEGIN --><details class="langpick">'
            '<summary aria-label="Language"><span>English</span></summary>'
            f'<nav>{"".join(items)}</nav></details><!-- LANGPICK:END -->')


def lang_alternates(page_path):
    """hreflang links pairing the English page with its translated copies."""
    rows = [f'<link rel="alternate" hreflang="x-default" href="{SITE}/{page_path}">',
            f'<link rel="alternate" hreflang="en" href="{SITE}/{page_path}">']
    rows += [f'<link rel="alternate" hreflang="{code}" href="{SITE}/{code}/{page_path}">'
             for code in SITE_LANGUAGES]
    return "\n".join(rows)

def render_sitemap(posts):
    today = max(p["date"] for p in posts)
    urls = [(f"{SITE}/", "1.0", today), (f"{SITE}/install", "0.9", today),
            (f"{SITE}/docs", "0.9", today),
            (f"{SITE}/compare", "0.8", today), (f"{SITE}/blog/", "0.8", today),
            (f"{SITE}/releases", "0.6", today), (f"{SITE}/roadmap", "0.6", today)]
    urls += [(post_url(p), "0.7", p["date"]) for p in posts]
    # Every translated copy, a notch below its English original. The language
    # list is duplicated from site-i18n.py rather than imported: this script is
    # the one that must keep running if that one is ever dropped.
    for code in ("zh-Hans", "zh-Hant", "ru", "ja", "de", "fr", "es", "ko", "pt-BR"):
        for path, pr in (("", "0.9"), ("docs", "0.8"), ("compare", "0.7"),
                         ("releases", "0.5"), ("roadmap", "0.5")):
            urls.append((f"{SITE}/{code}/{path}", pr, today))
    body = "\n".join(f'  <url><loc>{u}</loc><lastmod>{d}</lastmod>'
                      f'<priority>{pr}</priority></url>' for u, pr, d in urls)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f'{body}\n</urlset>\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify generated files are up to date; exit 1 if not")
    ap.add_argument("--list-icons", action="store_true")
    ap.add_argument("--stats", "--downloads", dest="stats", action="store_true",
                    help="also refresh the download + star counts from the GitHub "
                         "API (needs network; left alone otherwise)")
    args = ap.parse_args()

    if args.list_icons:
        print("icons: ", ", ".join(sorted(ICONS)))
        print("colors:", ", ".join(sorted(COLORS)))
        return

    releases = json.loads(DATA.read_text(encoding="utf-8"))["releases"]
    if not releases:
        sys.exit("releases.json: no releases")
    for r in releases:
        validate(r)
    versions = [r["version"] for r in releases]
    if sorted(versions, key=lambda v: [int(p) for p in v.split(".")], reverse=True) != versions:
        sys.exit("releases.json: releases must be ordered newest first")

    roadmap = json.loads(ROADMAP.read_text(encoding="utf-8"))
    validate_roadmap(roadmap)

    stats = json.loads(STATS.read_text(encoding="utf-8"))
    if args.stats:
        dl, st = fetch_download_total(), fetch_stars()
        if dl is not None:
            stats["downloads"] = dl
        if st is not None:
            stats["stars"] = st
        STATS.write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
    stars = stats["stars"]

    compare = json.loads(COMPARE.read_text(encoding="utf-8"))
    blog = json.loads(BLOG_JSON.read_text(encoding="utf-8"))
    blog_posts = sorted(blog["posts"], key=lambda x: x["date"], reverse=True)
    BLOG_DIR.mkdir(exist_ok=True)

    targets = {
        INDEX: patch_index(INDEX.read_text(encoding="utf-8"), releases[0], stats),
        INSTALL_HTML: render_install(releases[0]["version"], stats["downloads"], stars),
        COMPARE_HTML: render_compare(compare, stars),
        DOCS_HTML: render_docs(json.loads(DOCS_JSON.read_text(encoding="utf-8")), stars),
        BLOG_INDEX: render_blog_index(blog, stars),
        SITEMAP: render_sitemap(blog_posts),
        ROBOTS: render_robots(),
        CHROME_CSS_FILE: CHROME_CSS,
        HISTORY: render_history(releases, stars),
        ROADMAP_HTML: render_roadmap(roadmap, stars),
        README: patch_readme(README.read_text(encoding="utf-8"), roadmap),
    }
    for post in blog_posts:
        targets[BLOG_DIR / f'{post["slug"]}.html'] = render_blog_post(
            post, blog["categories"], blog_posts, stars)

    stale = [str(p.relative_to(ROOT)) for p, new in targets.items()
             if not p.exists() or p.read_text(encoding="utf-8") != new]

    if args.check:
        if stale:
            sys.exit(f"out of sync with docs JSON: {', '.join(stale)} "
                     f",  run python3 scripts/site-release.py and commit the result")
        print("site content is in sync")
        return

    for p, new in targets.items():
        p.write_text(new, encoding="utf-8")
    print(f"regenerated: {', '.join(stale) if stale else 'nothing changed'}")


if __name__ == "__main__":
    main()
